# Generated by Django 5.0.6 on 2024-05-26 17:51

import streamfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stream', streamfield.fields.StreamField(blank=True, default=list, verbose_name='Page blocks')),
                ('url', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
