# Generated by Django 4.2.3 on 2024-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_kwords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
