version: '3'

services:
   backend:
       build: backend/
       command: gunicorn config.wsgi:application --bind 0.0.0.0:80
       expose:
         - 80
       volumes:
         - static_volume:/app/backend/static
         - media_volume:/app/backend/media
       env_file:
         - .env
       depends_on:
         - db

   db:
     image: postgres:16.1-alpine3.19
     volumes:
       - postgres_data:/var/lib/postgresql/data/
     env_file:
       - .env
     environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_NAME}

   nginx:
     image: nginx:1.25.3-alpine
     hostname: config
     ports:
       - "80:80"
     volumes:
       - static_volume:/app/static
       - media_volume:/app/media
       - ./var/log/nginx:/var/log/nginx
       - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./volumes/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
       - ./volumes/etc/nginx/ssl:/etc/nginx/ssl
       - /var/www/DOMAIN_NAME:/var/www/DOMAIN_NAME
     depends_on:
       - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: