version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - static_files:/app/prod
    depends_on:
      - backend
    expose:
      - 3000

  backend:
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_files:/app/backend/static
      - media_volume:/app/backend/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    build: ./nginx
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - static_files:/usr/share/nginx/html
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_files:
  media_volume: